// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using MailTemplateHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailTemplateHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709022653_ApiKeys")]
    partial class ApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_keys_user_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access");

                    b.Property<byte[]>("ChecksumSha256")
                        .HasColumnType("bytea")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("PublicUrl")
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("upload_state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_storage_key");

                    b.HasIndex("UploadState", "CreatedAt")
                        .HasDatabaseName("ix_assets_pending");

                    b.HasIndex("UserId", "ChecksumSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_assets_user_checksum")
                        .HasFilter("deleted_at IS NULL AND upload_state = 'Ready'");

                    b.HasIndex("UserId", "Kind")
                        .HasDatabaseName("ix_assets_user_id_kind")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_action_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_user_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email_address");

                    b.PrimitiveCollection<List<string>>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("granted_scopes");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("StateReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state_reason");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_connected_email_accounts");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_connected_email_accounts_one_default")
                        .HasFilter("is_default AND deleted_at IS NULL");

                    b.HasIndex("UserId", "Provider", "ProviderAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_connected_email_accounts_user_id_provider_provider_account_")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("connected_email_accounts", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailProviderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConnectedEmailAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_email_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_error_code");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("RetryAfterSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_after_seconds");

                    b.Property<Guid?>("SendJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("send_job_id");

                    b.HasKey("Id")
                        .HasName("pk_email_provider_events");

                    b.HasIndex("ConnectedEmailAccountId", "CreatedAt")
                        .HasDatabaseName("ix_email_provider_events_connected_email_account_id_created_at");

                    b.HasIndex("SendJobId", "CreatedAt")
                        .HasDatabaseName("ix_email_provider_events_send_job_id_created_at");

                    b.ToTable("email_provider_events", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ContentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("disposition");

                    b.Property<string>("FilenameOverride")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename_override");

                    b.Property<Guid>("SendJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("send_job_id");

                    b.HasKey("Id")
                        .HasName("pk_email_send_attachments");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_email_send_attachments_asset_id");

                    b.HasIndex("SendJobId", "AssetId", "Disposition")
                        .IsUnique()
                        .HasDatabaseName("ux_send_attachments_unique");

                    b.ToTable("email_send_attachments", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConnectedEmailAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_email_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text")
                        .HasColumnName("failure_message");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("RenderedSnapshotKey")
                        .HasColumnType("text")
                        .HasColumnName("rendered_snapshot_key");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectSnapshot")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject_snapshot");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<long?>("TotalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<JsonDocument>("VariableValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variable_values");

                    b.HasKey("Id")
                        .HasName("pk_email_send_jobs");

                    b.HasIndex("ConnectedEmailAccountId")
                        .HasDatabaseName("ix_email_send_jobs_connected_email_account_id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_send_jobs_due")
                        .HasFilter("status = 'Scheduled'");

                    b.HasIndex("TemplateVersionId")
                        .HasDatabaseName("ix_email_send_jobs_template_version_id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_send_jobs_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_email_send_jobs_user_id_status_created_at");

                    b.ToTable("email_send_jobs", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email_address");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text")
                        .HasColumnName("failure_message");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("ProviderThreadId")
                        .HasColumnType("text")
                        .HasColumnName("provider_thread_id");

                    b.Property<Guid>("SendJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("send_job_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<JsonDocument>("VariableOverrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variable_overrides");

                    b.HasKey("Id")
                        .HasName("pk_email_send_recipients");

                    b.HasIndex("EmailAddress")
                        .HasDatabaseName("ix_email_send_recipients_email_address");

                    b.HasIndex("SendJobId", "EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_send_recipients_job_email");

                    b.HasIndex("SendJobId", "Status")
                        .HasDatabaseName("ix_email_send_recipients_send_job_id_status");

                    b.ToTable("email_send_recipients", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_templates");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_email_templates_current_version_id");

                    b.HasIndex("UserId", "IsArchived")
                        .HasDatabaseName("ix_email_templates_user_id_is_archived")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_email_templates_user_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EditorKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("editor_kind");

                    b.Property<JsonDocument>("GrapesProject")
                        .HasColumnType("jsonb")
                        .HasColumnName("grapes_project");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("MjmlSource")
                        .HasColumnType("text")
                        .HasColumnName("mjml_source");

                    b.Property<string>("Preheader")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preheader");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<JsonDocument>("VariablesSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_schema");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_email_template_versions");

                    b.HasIndex("TemplateId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_template_versions_number");

                    b.ToTable("email_template_versions", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.OAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PkceVerifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pkce_verifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ReturnTo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("return_to");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_states");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_oauth_states_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_oauth_states_user_id");

                    b.ToTable("oauth_states", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.OAuthToken", b =>
                {
                    b.Property<Guid>("ConnectedEmailAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_email_account_id");

                    b.Property<byte[]>("AccessTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_ciphertext");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<byte[]>("AccessTokenNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_nonce");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("KekVersion")
                        .HasColumnType("integer")
                        .HasColumnName("kek_version");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed_at");

                    b.Property<int>("RefreshFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_failure_count");

                    b.Property<byte[]>("RefreshTokenCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_ciphertext");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<byte[]>("RefreshTokenNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_nonce");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("ConnectedEmailAccountId")
                        .HasName("pk_oauth_tokens");

                    b.HasIndex("AccessTokenExpiresAt")
                        .HasDatabaseName("ix_oauth_tokens_access_token_expires_at");

                    b.ToTable("oauth_tokens", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.TemplateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ContentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usage");

                    b.HasKey("Id")
                        .HasName("pk_template_assets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_template_assets_asset_id");

                    b.HasIndex("TemplateVersionId", "AssetId", "Usage")
                        .IsUnique()
                        .HasDatabaseName("ux_template_assets_unique");

                    b.ToTable("template_assets", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.Asset", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_users_user_id");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connected_email_accounts_users_user_id");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailProviderEvent", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedEmailAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_provider_events_connected_email_accounts_connected_em");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendAttachment", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_send_attachments_assets_asset_id");

                    b.HasOne("MailTemplateHub.Domain.Entities.EmailSendJob", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SendJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_send_attachments_email_send_jobs_send_job_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendJob", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", "Account")
                        .WithMany()
                        .HasForeignKey("ConnectedEmailAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_send_jobs_connected_email_accounts_connected_email_ac");

                    b.HasOne("MailTemplateHub.Domain.Entities.EmailTemplateVersion", "TemplateVersion")
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_send_jobs_email_template_versions_template_version_id");

                    b.Navigation("Account");

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendRecipient", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.EmailSendJob", null)
                        .WithMany("Recipients")
                        .HasForeignKey("SendJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_send_recipients_email_send_jobs_send_job_id");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplate", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.EmailTemplateVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_templates_email_template_versions_current_version_id");

                    b.HasOne("MailTemplateHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_templates_users_user_id");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplateVersion", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.EmailTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_template_versions_email_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.OAuthState", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_states_users_user_id");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.OAuthToken", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", "Account")
                        .WithOne("Token")
                        .HasForeignKey("MailTemplateHub.Domain.Entities.OAuthToken", "ConnectedEmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_tokens_connected_email_accounts_connected_email_accou");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.TemplateAsset", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_template_assets_assets_asset_id");

                    b.HasOne("MailTemplateHub.Domain.Entities.EmailTemplateVersion", null)
                        .WithMany("TemplateAssets")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_assets_email_template_versions_template_version_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("MailTemplateHub.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.ConnectedEmailAccount", b =>
                {
                    b.Navigation("Token");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailSendJob", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.EmailTemplateVersion", b =>
                {
                    b.Navigation("TemplateAssets");
                });

            modelBuilder.Entity("MailTemplateHub.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
